### ISSUE TITLE
Is there option to allow only certain country for the picker?

### ISSUE THREAD

**Issue by jnickzlim** [biessek/flutter_country_picker#18]
I am wondering if there are option to allow configuration on allow which country to be in the selection dialog?

**Comment by jnickzlim** [comment]
Hello?

**Comment by biessek** [comment]
Not for now, actually it uses Country.ALL always. PR welcome.

**Comment by wintermuteturbo** [comment]
Hi @biessek,
In my PR I've added new param ```limitCountries``` which accepts list of countries like ```['IE', 'US', 'PL']``` and limits selection to listed countries if not specified defaults to ```Country.ALL```.
