### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by LiveRock** [biessek/flutter_country_picker#2]
Can't build ios with this error:

The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

If I open the project in ios, the error is:

The target “flutter_country_picker” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

**Comment by biessek** [comment]
I am without mac os at the moment, but I will try to rent one and resolve it as soon as possible, thanks for the warning.

**Comment by biessek** [comment]
I checked in version 9.4.1 and could compile normally, it should be something in your configuration, 
I could not find anything else. 

Also, in my project the version of Swift is 4.0..

**Comment by saswatsaubhagya** [comment]
no bro still the same issue

**Comment by megablinkk** [comment]
I have the same issue.

EDIT : Fixed it based on this : https://github.com/flutter/flutter/issues/16049#issuecomment-382664356
