### ISSUE TITLE
Are you planning to add more attributes to the country class?

### ISSUE THREAD

**Issue by andreskiu** [biessek/flutter_country_picker#21]
Is just a question,
Could be useful to add Language and Time Zone, for example, for each country.

**Comment by biessek** [comment]
No, for now, many language/date/currency info can be obtained from the platfor, Locale and util classes. 
The main point of this lib is to provide dialing codes that are useful to specific cases, like contact management, phone login..

**Comment by andreskiu** [comment]
thanks!
