### ISSUE TITLE
Error: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'flutter_country_picker' is using version 1.2.30.

### ISSUE THREAD

**Issue by anoop4real** [biessek/flutter_country_picker#5]
I am using Android studio 3.2. Getting the below error in Android.

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'flutter_country_picker' is using version 1.2.30.

**Comment by sammymwangangi** [comment]
Am facing the same issue

**Comment by biessek** [comment]
Thanks for reporting the issue.

Please, check if version 0.1.2 works for you.
